- hooli_data_eng/assets/marketing/__init__.py
- hooli_data_eng/repository.py
- adds two new assets under marketing with freshness policies
- one asset is tracked by a reconciliation sensor to show how its policy will trigger runs (the policy requires data less fresh than the schedule on the orders_augmented dataset, so the freshness policy should only update the intermediate marketing assets)
- the other asset has a freshness policy but is not tracked by a reconciliation sensor, showing how policies can cause a late status
> add in freshness policies

- dbt_project/models/ANALYTICS/daily_order_summary.sql
- dbt_project/models/ANALYTICS/orders_augmented.sql
- dbt_project/models/CLEANED/orders_cleaned.sql
- hooli_data_eng/assets/dbt_assets.py
- hooli_data_eng/assets/forecasting/__init__.py
- hooli_data_eng/assets/marketing/__init__.py
- hooli_data_eng/assets/raw_data/__init__.py
- hooli_data_eng/definitions.py
- hooli_data_eng/resources/api.py
- hooli_data_eng/utils/__init__.py
Adds hourly and daily partitions to the relevant EL assets and dbt assets. Also adds an example of a dynamic partition.
Of note:
- updates the dbt models to include incremental updates, includes an example of daily partitions rolling into hourly partitions
- adds a mapping between dagster partitions, dbt vars, and partition_expr metadata
- adds a dynamic partition to pull reports by product sku
- refactors the random data to present meaningful skus and partition-correct date times
> Add partitions

- hooli_data_eng/assets/dbt_assets.py
- hooli_data_eng/assets/raw_data/__init__.py
- hooli_data_eng/resources/api.py
- hooli_data_eng_tests/test_assets.py
This PR makes it possible for a single run to backfill multiple partitions of the orders and users assets.
In order to do this the best approach is to write code that can handle a range of partitions but also works correctly when that "range" is a single partition. 
I also added unit tests for both cases.
Follow on work is needed for the dbt assets to support the same capabilities.
For the sake of sanity, I added an option for the flakiness in the fake data api to be disabled. While this flakiness is useful for demoing dagster's retry policies, it makes unit tests very challenging. If only disabling flakiness were possible for real life.
> allow for single run backfills

- dbt_project/models/ANALYTICS/daily_order_summary.sql
- dbt_project/models/ANALYTICS/order_stats.sql
- dbt_project/models/ANALYTICS/sku_stats.sql
- dbt_project/models/MARKETING/company_perf.sql
- hooli_data_eng/assets/dbt_assets.py
- hooli_data_eng/assets/marketing/__init__.py
- hooli_data_eng/assets/raw_data/__init__.py
- hooli_data_eng/definitions.py
- hooli_data_eng/resources/api.py
- hooli_data_eng_tests/test_assets.py
This PR does a few things
1. Deprecates the reconciliation sensor in favor of the AutoMaterialize policies
2. Fixes the unit tests for the user and order assets which were broken by the resource config re-write
3. Resets the partition definitions to a later date
The change to (1) should also dramatically simplify the behavior we're seeing on hooli where the root assets were being updated by both a schedule and freshness sensor, causing confusing discrepancies between run statuses and partition statuses.
> Lopp automaterialize

- hooli_data_eng/assets/dbt_assets.py
- hooli_data_eng/assets/raw_data/__init__.py
> launch week fixes

- dbt_project/models/ANALYTICS/company_stats.sql
- dbt_project/models/ANALYTICS/order_stats.sql
- dbt_project/models/ANALYTICS/sku_stats.sql
- dbt_project/models/ANALYTICS/weekly_order_summary.sql
- dbt_project/models/MARKETING/company_perf.sql
- hooli_data_eng/assets/dbt_assets.py
- hooli_data_eng/assets/marketing/__init__.py
This PR addresses some long standing problem's in Hooli's use of experimental auto-materialization policies, specifically the case of daily partitioned assets -> weekly partitioned assets -> unpartitioned assets. 
The customized policy now makes it so that any change to a daily partition will cause downstream assets to materialize, essentially making AMPs more aggressive. This change helps us demo how changes propagate through the system. 
We also remove lazy policies which just didn't work in these situations.
Tradeoffs:
The remaining freshness policies are now useful for alerting only, they no longer dictate run behavior.
The change to use a customized AMP means the AMP policies must be defined in code and not in the dbt model config.
> make amps work better for hooli

- .github/workflows/deploy-dagster-cloud.yml
- dagster_cloud.yaml
- dbt_project/dbt_project.yml
- hooli_data_eng/assets/dbt_assets.py
- hooli_snowflake_insights/Dockerfile
- hooli_snowflake_insights/definitions.py
- hooli_snowflake_insights/requirements.txt
- requirements.txt
- setup.py
Created a separated code location for snowflake insights functionality
> Add snowflake insights

- hooli_data_eng/assets/dbt_assets.py
- hooli_data_eng/resources/__init__.py
- hooli_data_eng/resources/dbt.py
- hooli_data_eng/resources/warehouse.py
> clean up dbt

- dbt_project/models/CLEANED/locations_cleaned.sql
- dbt_project/models/sources.yml
- hooli-demo-assets/hooli_demo_assets/assets/sling.py
- hooli-demo-assets/hooli_demo_assets/jobs/__init__.py
Updated sling asset name to be consistent with other raw data naming conventions
> updated sling asset name

- dbt_project/models/CLEANED/schema.yml
- dbt_project/tests/assert_total_order_non_zero.sql
- dbt_project/tests/generic/test_greater_than_zero.sql
- hooli_data_eng/assets/dbt_assets.py
this PR shows how dbt generic tests (both built in and custom) become dagster asset checks
right now all checks are on the asset `orders_cleaned`
note that the singular dbt test, `assert_total_order_non_zero.sql` does not become an asset check, per https://github.com/dagster-io/dagster/issues/18595
> add dbt tests as asset checks

- .github/workflows/deploy-dagster-cloud.yml
- hooli_data_eng/assets/dbt_assets.py
- hooli_data_eng/assets/forecasting/__init__.py
- hooli_data_eng/definitions.py
Adding dbt slim CI functionality.  
High level process:
- Copy production manifest.json to S3
- Created @op and @job to use dbt's state deferral syntax (e.g., dbt build --select state:modified+ --defer --state <path/to/prod_manifest.json> ), since assets don't currently support it
- GitHub Action:
- Reads production manifest.json from S3 
- Generates new manifest.json with code changes
- Triggers op job above using the two manifests for comparison and only materialize new dbt models + downstream dependencies
> WIP adding dbt slim CI job

- dbt_project/models/CLEANED/locations_cleaned.sql
- dbt_project/models/CLEANED/schema.yml
- hooli_data_eng/assets/dbt_assets.py
Add compiled SQL for dbt models to the event logs
> Add compiled SQL for dbt models to the event logs

- hooli_data_eng/assets/raw_data/__init__.py
This PR updates the asset check on the `RAW_DATA.users` asset in a few ways
*  compares the types to a set (previously it would almost always fail because lists are unordered)
* forces it to fail by omitting one of the observed companies in the expected companies, _and_ by adding an expected company that is not in observed
* **this one I want feedback on** -- I added a markdown data element (see the image below) after following along with some of the cool metadata output types @slopp wrote up [in this GitHub Discussion](https://github.com/dagster-io/dagster/discussions/15409). I wanted to show the "in expected not observed" and "in observed not expected" in some sort of way to show off how powerful the metadata exposures can be, but the data frame --> markdown I did here leaves a lot to …
> update dagster asset check to fail"better"

- hooli_data_eng/assets/dbt_assets.py
- hooli_data_eng/assets/marketing/__init__.py
This PR adopts the new asset `owners` field which allows for asset alerts and populates the `owners` information in the new asset details view
Still TBD:
> update owners to new asset owners

- README.md
- hooli-demo-assets/hooli_demo_assets/resources/__init__.py
- setup.py
the Sling loader was failing in prod, and I wanted to debug it. There must have been an update to Sling between version upgrades because we needed to change the AWS_BUCKET from `s3://{bucket_name}/{folder_path}` (old) to just `{bucket_name}`. That was an env var change which is now live, but for me to figure that out I had to get the local version working. This PR adds that local support:
* updates the extras in `setup.py` to include `dagster-embedded-elt`
* adds a local duckdb target and makes local dev supportable
* updates the README.md
> add local dev and update docs for Sling

- hooli_data_eng/assets/dbt_assets.py
when we refactored the code to remove the older dbt APIs, we accidentally made our dbt views into weekly partitioned assets, which causes problems since they are upstream of some daily partitioned assets
> fix partition mismatch for dbt

- hooli-demo-assets/setup.py
- hooli_basics/requirements.txt
- hooli_batch_enrichment/setup.py
- hooli_snowflake_insights/requirements.txt
- setup.py
adds dagster-cloud[insights] extra to all installs of dagster-cloud. We might only need it in `hooli_snowflake_insights`, and it's redundant for `hooli_data_eng` because it already has pyarrow from other dependencies
> add insights extra to dasgter-cloud

- .gitignore
- hooli-demo-assets/hooli_demo_assets/assets/sling.py
- hooli-demo-assets/hooli_demo_assets/definitions.py
- hooli-demo-assets/hooli_demo_assets/jobs/__init__.py
- hooli-demo-assets/hooli_demo_assets/resources/__init__.py
- hooli-demo-assets/hooli_demo_assets/schedules/__init__.py
Updating the Sling demo to the new APIs.
Summary of updates:
- added replication python config
- updated SlingResource to use SlingConnectionResource instead of SlingSourceConnection/SlingTargetConnection (soon to be deprecated)
- add custom sling translator to modify the default asset key (prefix with "RAW_DATA")
- updated sling assets to use the sling_assets decorator
There seems to be a bug with local dev when including a target schema with duckdb — "Catalog Error: Schema with name "raw_data" already exists!"
> Update sling assets

- dbt_project/packages.yml
brings us plotting of number of failures for dbt test results
Looks like this 
and will also show up in insights
> bump dagster version to 1.7.8

- hooli_data_eng/assets/forecasting/__init__.py
- hooli_data_eng/assets/marketing/__init__.py
- hooli_data_eng/assets/raw_data/__init__.py
- hooli_data_eng/utils/config_utils.py
Adding `storage_kind` to non-dbt assets in the `hooli_data_eng` code location.
Summary of changes:
- Added `config_utils.py` to dynamically generate storage_kind (duckdb or snowflake) based on deployment (local or branch/prod)
- Added storage_kind to non-dbt assets where the `compute_kind` didn't make this obvious
One thing to note, I defaulted the storage_kind to S3 for assets using the `model_io_manager` since it uses the `FilesystemIOManager()` locally and S3 in branch and prod deployments.
> Add storage_kind tag

- .github/workflows/deploy-dagster-cloud.yml
Pre, with 2 warnings:
Post, with 1 warning: 🎉 
I also added the docker-buidx step that is present in [our example](https://github.com/dagster-io/dagster-cloud-hybrid-quickstart/blob/main/.github/workflows/dagster-cloud-deploy.yml), though it doesn't seem to speed anything up so I'm not sure what it's purpose is.
> bump versions and add caching

- hooli_data_eng/definitions.py
- hooli_data_eng/sensors/__init__.py
- hooli_data_eng/utils/dbt_code_version.py
This PR adds a sensor that evaluates the hash value of the current state of the dbt code against the code version of the previous materialization. This is a way that you could leave dbt views unscheduled but update them anytime there is a change in the code.
I don't think this is absolutely core functionality for the demo project, but it has come up a few times and I wanted to show a solid solution in this space
> Add a sensor for dbt views

- .github/workflows/deploy-dagster-cloud.yml
- hooli-demo-assets/hooli_demo_assets/definitions.py
- hooli-demo-assets/hooli_demo_assets/resources/__init__.py
- hooli_basics/definitions.py
- hooli_batch_enrichment/dagster_batch_enrichment/definitions.py
- hooli_data_eng/assets/dbt_assets.py
- hooli_data_eng/definitions.py
- hooli_data_eng/sensors/__init__.py
- hooli_data_eng/utils/dbt_code_version.py
- hooli_snowflake_insights/definitions.py
- workspace.yaml
This change allows you to link back to an asset's source code from Dagster's UI.
This [utility](https://benpankow-code-references-git.dagster.dagster-docs.io/guides/dagster/code-references#in-dagster-plus) will automatically detect if your code is running in a Dagster Cloud environment and convert local file code references to source control links, pointing at the commit hash of the code running in the current deployment.
> Add links to source code

- dbt_project/dbt_project.yml
- hooli_data_eng/project.py
- hooli_data_eng/resources/__init__.py
Per the docs of [1.7.13](https://github.com/dagster-io/dagster/releases/tag/1.7.13):
> [dagster-dbt] During development,DbtProject no longer prepares the dbt manifest file and dbt dependencies in its constructor during initialization. This process has been moved to prepare_if_dev(), that can be called on the DbtProject instance after initialization. Check out the API docs for more: [https://docs.dagster.io/_apidocs/libraries/dagster-dbt#dagster_dbt.DbtProject.prepare_if_dev](https://docs.dagster.io/_apidocs/libraries/dagster-dbt#dagster_dbt.DbtProject.prepare_if_devhttps://docs.dagster.io/_apidocs/libraries/dagster-dbt#dagster_dbt.DbtProject.prepare_if_dev).
@izzye84  already did the other piece in #100, of switching the dagster-dbt CLI arguments. 
This won't have an impact on branch …
> Add prepare if dev dbt

- Dockerfile
- hooli-demo-assets/Dockerfile
- hooli_basics/Dockerfile
- hooli_batch_enrichment/Dockerfile
- hooli_snowflake_insights/Dockerfile
- setup.py
bumps images to use python 3.12 except for one code location (to show that we don't have to run the same versions). 
Also bumps to dagster 1.7.14
> bump to 3.12

- hooli-demo-assets/hooli_demo_assets/resources/__init__.py
to ensure that we always target `"BRANCH"` in github action CI, let it be the default of `get_env` and instead detect local development by looking for the `dagster dev` env var
> change dbt target resolution

- hooli-demo-assets/hooli_demo_assets/resources/__init__.py
- hooli_data_eng/project.py
https://github.com/dagster-io/hooli-data-eng-pipelines/pull/112/ but this time in the right file
print the args before dbt runs them and verify that i see `'dbt', '--target', 'BRANCH'` when i run ` dagster-dbt project prepare-and-package --file hooli_data_eng/project.py`
> change dbt target resolution take 2

- dbt_project/models/CLEANED/locations_cleaned.sql
- dbt_project/models/CLEANED/orders_cleaned.sql
- dbt_project/models/CLEANED/users_cleaned.sql
- dbt_project/models/FORECASTING/all_orders.sql
- dbt_project/models/sources.yml
Not sure why this change suddenly happened, but the case mismatch in the dbt source vs. the actual identifier was causing issues
> lowercase schema to fix column level lineage

- README.md
- hooli-demo-assets/hooli_demo_assets/resources/__init__.py
- hooli-demo-assets/locations.csv
- hooli_data_eng/assets/dbt_assets.py
- hooli_data_eng/assets/marketing/__init__.py
- hooli_data_eng/sensors/__init__.py
The past version of hooli relied on auto-materialization policies. Primarily these policies were based on the default eager auto-materialization strategy, with some customization to prevent missing or outdated partitions from blocking downstream non-partitioned asset runs. The root assets were run by a cron schedule, with most changes propagating through downstream assets daily.
This PR replaces those auto-materialization policies with their counter-part automation conditions. The PR also adds some complexity to introduce new automation scenarios, specifically: 
- The core assets `orders, orders_cleaned, users, users_cleaned, and orders_augmented` are still scheduled by a daily job
- `company_stats` remains eager, and should see changes propagated daily
- `location_stats` remains eager, …
> Moving from auto materialization to automation conditions

- Makefile
I am lazy. 
Sometimes I want to dogfood / try out unreleased versions of Dagster in hooli, and my process annoyed me
old process:
`cd $DAGSTER_GIT_REPO_DIR`
`make dev_install`
wait
`cd -`
proposed process:
`make install_from_dagster_clone`
profit
> add install_from_dagster_clone makefile command

- .github/workflows/deploy-dagster-cloud.yml
Summary:
For reasons that are not entirely clear to me, the previous command was leaving pip on 20.0.2 and not actually upgrading it.
Test Plan: Should now build and deploy without CI/CD hack
> Correctly upgrade pip in hooli CI/CD

- hooli-demo-assets/hooli_demo_assets/assets/sling.py
released in 1.8.1, sling assets can now show column level lineage and column metadata.
Will add row count once the release it live this week or next
> add column metadata and lineage to sling

- hooli_data_eng/blueprints/blueprints.py
- hooli_data_eng/blueprints/blueprints_jobs/dbt_job.yaml
- hooli_data_eng/definitions.py
- setup.py
This blueprints example constructs a dbt job for any yaml file with the appropriate config under the `hooli_data_eng/blueprints/blueprints_jobs/` directory—the job config is defined by the `DbtSelectScheduledJobBlueprint` class.
> dbt blueprints example

- hooli-data-ingest/hooli_data_ingest/assets/sling.py
- hooli_basics/definitions.py
- hooli_batch_enrichment/dagster_batch_enrichment/assets.py
- hooli_data_eng/assets/forecasting/__init__.py
- hooli_data_eng/assets/marketing/__init__.py
- hooli_data_eng/assets/raw_data/__init__.py
- hooli_data_eng/utils/kind_helpers.py
moves from using `**build_kind_tags` to `kinds=` wherever possible. Currently seems like Sling and dagstermill are the two exceptions.
Tested locally by making sure that the kind tags did what I expected
> Use better kind api

- pyproject.toml
The GitHub action erroneously performs `ruff` formatting on the `github` directory.
This introduces a Ruff configuration in `pyproject.toml` to exclude those files from being formatted.
> Exclude .github/ directory in Ruff formatting

- dg.toml
Hooli is yelling at us during dg operations because it uses the old plugin entry point. This doesn't do any harm unless we want to demo the pyproject.toml itself.
Suppressing it for now.
Test Plan:
Before:
```
(hooli-data-eng) ➜  hooli-data-eng git:(master) dg list defs
Found deprecated `dagster_dg.plugin` entry point group in:
/Users/schrockn/code/hooli-data-eng-pipelines/hooli-data-eng/pyproject.toml
Please update the group name to `dagster_dg_cli.registry_modules`. Package reinstallation is required
because entry points are registered at install time. Reinstall your package to your
environment using:
[uv]  $ uv pip install -e .
[pip] $ pip install -e .
To suppress this warning, add "deprecated_dagster_dg_library_entry_point" to the `cli.suppress_warnings` list in your configuration. …
```
> Suppress warnings in hooli dg cli

- hooli-data-eng/hooli_data_eng/defs/dbt/component.py
Moving dbt assets to a component introduced a bug for non-partitioned dbt assets that result in an error—`dagster._core.errors.DagsterInvariantViolationError: Partitions definition is not defined`.  
This PR fixes that bug by conditionally checking if the underlying asset has partitions before invoking the `dbt build` command.
> fixed bug for non-partitioned dbt assets
